### ISSUE TITLE
How to deploy to legacy keepalived?

### ISSUE THREAD

**Issue by liuzhen** [gen2brain/keepalived_exporter#1]
We have multiple instance in our prod, and not built with any extra flags.
Any workaround?

**Comment by gen2brain** [comment]
No workaround currently. It is possible to add an option for the exporter, to send a different SIGNAL to KA, and then to add functions to parse some text files instead of decoding JSON.

I do not need that, so not sure when will I find time to add such option.

**Comment by gen2brain** [comment]
Text files parsing is implemented in https://github.com/gen2brain/keepalived_exporter/commit/a8b3e1304623dbc2b52baf7d63d1fef0faab680f and that is default now. JSON can be enabled with the `-ka.json` option. 

Let me know how it works and if there are issues.

**Comment by liuzhen** [comment]
Great.
