### ISSUE TITLE
Parse IP Error

### ISSUE THREAD

**Issue by mdp1230** [gen2brain/keepalived_exporter#11]
keepalived_exporter: destinations: parseIP Error ip=[192 168 1 10 0 0 0 0 0 0 0 0 0 0 0 0]

/etc/redhat-release
CentOS Linux release 7.5 and CentOS Linux release 7.7

**Comment by gen2brain** [comment]
This should be fixed in https://github.com/gen2brain/keepalived_exporter/commit/f9851ed1942210e2c5f4ba10d441c5544c4cbbfb
