### ISSUE TITLE
Can not open /tmp/keepalived.data

### ISSUE THREAD

**Issue by mdp1230** [gen2brain/keepalived_exporter#12]
keepalived_exporter: open /tmp/keepalived.data: no such file or directory
open /tmp/keepalived.stats is okay.

CentOS Linux release 7.5

**Comment by nlameiras** [comment]
Note: if SELinux is used (CentOS 7), it does not allow writing to this file. You can get around this with this preparation:

touch /tmp/keepalived.stats
chmod go+w /tmp/keepalived.stats
semanage fcontext -a -t keepalived_var_run_t /tmp/keepalived.stats
restorecon /tmp/keepalived.stats

Now try sending the signal again.

source : https://serverfault.com/a/987592

**Comment by gen2brain** [comment]
Sorry, support for parsing text files is removed.
