### ISSUE TITLE
PID retrieval error

### ISSUE THREAD

**Issue by gunhu** [gen2brain/keepalived_exporter#13]
On a brand new Debian GNU/Linux Buster node under certain circumstances.

I got the following error message:

- Apr 24 17:45:23 dzr-lvs-01 deezer-keepalived-exporter[21990]: 2020/04/24 17:45:23 keepalived_exporter: open /proc/2134/status: no such file or directory

After checking the relevant code is producing the error message:

```
	for _, p := range ps {
		name, err := p.Name()
		if err != nil {
			return err
		}
```

I would like to submit a PR and fetch the PID directly from the keepalived pid file located under /var/run directory.

Is it a suitable fix for you?

Regards,

**Comment by gen2brain** [comment]
This should be fixed in https://github.com/gen2brain/keepalived_exporter/commit/3b13ebe40de588e107d972ddfa9d314c9baf9462 . Hardcoding PID file location is not a good idea, especially if KA supports an option for that (`-p`) so the user can change it.
