### ISSUE TITLE
The exporter requires to run as "root" to work

### ISSUE THREAD

**Issue by kodachimaru** [gen2brain/keepalived_exporter#14]
If I run it as a non root user, I get this error

```text
prometheus-keepalived-exporter[14775]: time="2022-05-31T10:21:39Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."
prometheus-keepalived-exporter[14775]: time="2022-05-31T10:21:39Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: ERROR: could not insert 'ip_vs': Operation not permitted\ninsmod /lib/modules/4.19.0-16-amd64/kernel/lib/libcrc32c.ko`, error: exit status 1"
```

And the only metric returned is

```text
keepalived_up 0
```

If I run it as "root" instead, the exporter works just fine. But obviously I don't wanna run it as root...

I think that the exporter should not try to use "insmod", maybe just log the missing module and exit. Whoever is installing the exporter will ensure that the required module is present before running it.

**Comment by gen2brain** [comment]
You can see here how to enable CAP capabilities https://github.com/gen2brain/keepalived_exporter/issues/5#issuecomment-579293035 instead of running as root. The exporter is not doing `insmod`, KA is doing it.

**Comment by gen2brain** [comment]
The perfect combination is to not run Keepalived as root, that is first, run as some user as in that comment, and run exporter as the same user.

**Comment by kodachimaru** [comment]
Will do that. Thx for the quick answer.
