### ISSUE TITLE
keepalived_up is sometimes 0

### ISSUE THREAD

**Issue by Bagani** [gen2brain/keepalived_exporter#15]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/28551599/233818306-6c44ad07-031f-4c81-8b6d-26f6affd9da6.png">
As shown in the figure, it is 0 at one time and 1 at another time, which leads to promthues misreporting

**Comment by gen2brain** [comment]
The whole point of `keepalived_up` is to show whether the service is up or not. What is the issue here?
