### ISSUE TITLE
Dashboard for grafana

### ISSUE THREAD

**Issue by alexmayerlab** [gen2brain/keepalived_exporter#2]
is there a dashboard for grafana?

**Comment by gen2brain** [comment]
No, I just use one panel, like this one:
![screen04](https://user-images.githubusercontent.com/17418/67968563-ec3e7e80-fc07-11e9-9580-e54b67102511.png)

If you do create a dashboard it would be nice to add to examples here.

**Comment by bhozar** [comment]
@alexmayerlab @gen2brain I've recently setup the exporter and created a basic dashboard. Obviously it may not work for your usage scenario. It also does not include any LVS metrics as we are using keepalived on Azure VM's.

https://github.com/bhozar/grafana-dashboards/tree/master/keepalived
