### ISSUE TITLE
Service periodically stops responding

### ISSUE THREAD

**Issue by alexmayerlab** [gen2brain/keepalived_exporter#4]
Service periodically stops responding,
in the logs

**keepalived_exporter[2226]: 2019/11/01 06:16:40 genl hub loop exit**

After restarting the process, everything works

OS Centos 7, run from root

keepalived -v
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

Build options:  PIPE2 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_OIFNAME FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK LIBIPTC LIBIPSET_DYNAMIC LVS LIBIPVS_NETLINK VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING INET6_ADDR_GEN_MODE SNMP_V3_FOR_V2 SNMP SNMP_KEEPALIVED SNMP_CHECKER SNMP_RFC SNMP_RFCV2 SNMP_RFCV3 SO_MARK

**Comment by gen2brain** [comment]
This should be fixed in https://github.com/gen2brain/keepalived_exporter/commit/543273232c2e9d53f44eec5d4f7f631e224ec8e5 .

**Comment by alexmayerlab** [comment]
Everything works, thank you)
